apiVersion: v1
kind: Service
metadata:
  name: coworking
spec:
  type: LoadBalancer
  selector:
    service: coworking
  ports:
    - name: "5153"
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
  labels:
    name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
        - name: coworking
          # ECR image URI for your account
          image: 767398149973.dkr.ecr.us-east-1.amazonaws.com/coworking-analytics:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/readiness_check"
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: coworking-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: coworking-secret
                  key: DB_PASSWORD
      restartPolicy: Always
